#!/bin/sh

# Script to tar up the braidlab distribution files.
#   exclude LCS toolbox for now

TARCMD=tar

# release version:
VERSION=`hg tags | grep release | cut -b 9-13 | head -1 | sed 's/ *$//g'`

# test for compatibility of the mex command
if [[ -z $(mex -help | grep -n MATLAB) ]]
	then echo "Command 'mex' is not Matlab's MEX compiler. Instead it is, most likely, a latex-related command. Please make MEX compiler available in your execution path"; exit
fi

# build the braidlab user's guide
cd doc
make braidlab_guide.pdf
cd ..

# Make 32 and 64 bit, cross-compile for Mac, Windows (we wish).
# Or compile separately and add to subfolders.
make all

rm -f braidlab-${VERSION}.tar.gz braidlab-${VERSION}.zip
cd ..
${TARCMD} cvzf braidlab/braidlab-${VERSION}.tar.gz \
    --exclude='braidlab/+braidlab/+lcs' \
    braidlab/+braidlab \
    braidlab/README.md \
    braidlab/COPYING \
    braidlab/LICENSE \
    braidlab/Makefile \
    braidlab/Makefile.cbraid-mex \
    braidlab/testsuite \
    braidlab/extern/README \
    braidlab/extern/VariablePrecisionIntegers \
    braidlab/doc/braidlab_guide.pdf
cd braidlab

# Also make a zip.
mkdir tmp-zip
cd tmp-zip
${TARCMD} xvzf ../braidlab-${VERSION}.tar.gz
zip -r ../braidlab-${VERSION}.zip braidlab
cd ..
rm -rf tmp-zip
