#!/bin/sh

# Quick script to tar up the braidlab distribution files.
#   exclude version-control folders
#   exclude LCS toolbox for now
#   the README needs work

# set to a tar command that supports --exclude-vcs option, e.g., GNU tar
TARCMD=tar

VERSION=1.0.1

cd doc
pdflatex braidlab_guide.tex
bibtex braidlab_guide
pdflatex braidlab_guide.tex
pdflatex braidlab_guide.tex
cd ..

# Make 32 and 64 bit, cross-compile for Mac, Windows (we wish).
# Or compile separately and add to subfolders.
make all

rm -f braidlab-${VERSION}.tar.gz braidlab-${VERSION}.zip
cd ..
${TARCMD} cvzf braidlab/braidlab-${VERSION}.tar.gz \
    --exclude-vcs \
    --exclude='braidlab/+braidlab/+lcs' \
    braidlab/+braidlab \
    braidlab/README.md \
    braidlab/Makefile \
    braidlab/Makefile.cbraid-mex \
    braidlab/testsuite \
    braidlab/extern/braid-code \
    braidlab/extern/cbraid \
    braidlab/extern/trains \
    braidlab/extern/VariablePrecisionIntegers \
    braidlab/doc/braidlab_guide.pdf
cd braidlab

# Also make a zip.
mkdir tmp-zip
cd tmp-zip
${TARCMD} xvzf ../braidlab-${VERSION}.tar.gz
zip -r ../braidlab-${VERSION}.zip braidlab
cd ..
rm -rf tmp-zip
