#!/bin/bash

function howmanycom() {
	 VERGAP=$(git log --pretty=oneline $1..$2 | wc | cut -b -10)
	 printf "%-13s to %-13s: %5d commits\n" $1 $2 $VERGAP
}
export -f howmanycom

howmanycom release-2.1   HEAD
howmanycom release-2.0   release-2.1
howmanycom release-1.0.5 release-2.0
howmanycom release-1.0.4 release-1.0.5
howmanycom release-1.0.3 release-1.0.4
howmanycom release-1.0.2 release-1.0.3
howmanycom release-1.0.1 release-1.0.2
howmanycom release-1.0   release-1.0.1
