#!/bin/bash

# Insert the 'GNU boilerplate language' between two tags.
#
# Run this as
#
#  ./devel/insertboiler <base_directory>
#
# It will recurse down the directory.  The file COPYING needs to be in
# the folder where the command is executed.

ROOTDIR=$1
export BPFILE=COPYING

function checkboiler() {
    return $(grep --quiet LICENSE $1)
}
export -f checkboiler

function insertboiler_matlab() {
    export OPENTAG='% <LICENSE'
    export CLOSETAG='% LICENSE>'

    if !(checkboiler $1); then
	echo "Warning: file" $1 "is missing LICENSE tag."
	exit 1
    fi

    sed 's/^/%   /' ${BPFILE} >| ${BPFILE}.m
    sed -i "/${OPENTAG}/,/${CLOSETAG}/ {//!d}; /${OPENTAG}/r ${BPFILE}.m" $1
    rm -f ${BPFILE}.m
}
export -f insertboiler_matlab

function insertboiler_cpp() {
    export OPENTAG='\/\/ <LICENSE'
    export CLOSETAG='\/\/ LICENSE>'

    if !(checkboiler $1); then
	echo "Warning: file" $1 "is missing LICENSE tag."
	exit 1
    fi

    sed 's,^,//   ,' ${BPFILE} >| ${BPFILE}.cpp
    sed -i "/${OPENTAG}/,/${CLOSETAG}/ {//!d}; /${OPENTAG}/r ${BPFILE}.cpp" $1
    rm -f ${BPFILE}.cpp
}
export -f insertboiler_cpp

function insertboiler_c() {
    export OPENTAG='<LICENSE'
    export CLOSETAG='LICENSE>'

    if !(checkboiler $1); then
	echo "Warning: file" $1 "is missing LICENSE tag."
	exit 1
    fi

    sed 's,^,   ,' ${BPFILE} >| ${BPFILE}.c
    sed -i "/${OPENTAG}/,/${CLOSETAG}/ {//!d}; /${OPENTAG}/r ${BPFILE}.c" $1
    rm -f ${BPFILE}.c
}
export -f insertboiler_c

function insertboiler_bash() {
    export OPENTAG='# <LICENSE'
    export CLOSETAG='# LICENSE>'

    if !(checkboiler $1); then
	echo "Warning: file" $1 "is missing LICENSE tag."
	exit 1
    fi

    sed 's,^,#   ,' ${BPFILE} >| ${BPFILE}.sh
    sed -i "/${OPENTAG}/,/${CLOSETAG}/ {//!d}; /${OPENTAG}/r ${BPFILE}.sh" $1
    rm -f ${BPFILE}.sh
}
export -f insertboiler_bash

find $ROOTDIR -name "*.m" -print0 | \
    xargs -0 -n 1 bash -c 'insertboiler_matlab "$@"' _

find $ROOTDIR -name "*.cpp" -print0 | \
    xargs -0 -n 1 bash -c 'insertboiler_cpp "$@"' _

find $ROOTDIR -name "*.c" -print0 | \
    xargs -0 -n 1 bash -c 'insertboiler_c "$@"' _

# Use Matlab tags for latex and bibtex files.
find $ROOTDIR -name "*.tex" -print0 | \
    xargs -0 -n 1 bash -c 'insertboiler_matlab "$@"' _
find $ROOTDIR -name "*.bib" -print0 | \
    xargs -0 -n 1 bash -c 'insertboiler_matlab "$@"' _

find $ROOTDIR -name "Makefile" -print0 | \
    xargs -0 -n 1 bash -c 'insertboiler_bash "$@"' _

unset -f checkboiler
unset -f insertboiler_matlab
unset -f insertboiler_cpp
unset -f insertboiler_c
unset -f insertboiler_bash
unset BPFILE
unset OPENTAG
unset CLOSETAG
